// Generated by CoffeeScript 1.3.3
var Joint;

Joint = (function() {

  function Joint() {}

  Joint.bodies = new THREE.Object3D();

  return Joint;

})();

({
  constructor: function(axis, motorID) {
    var rotate;
    this.axis = axis;
    this.motorID = motorID;
    return rotate = function(radiants) {
      var matrix;
      matrix = new THREE.Matrix4().makeRotationAxis(axis, radiants);
      return bodies.setRotationFromMatrix(matrix);
    };
  }
});
