// Generated by CoffeeScript 1.3.3
var Robot, addBody, baseUrl, bodyQueue, loadNextBody, loader, rdfLoadingCallback;

bodyQueue = [];

loader = null;

baseUrl = 'js/rdf/robot2012/';

Robot = (function() {

  Robot.bodies = new THREE.Object3D();

  Robot.joints = [];

  Robot.isInitialized = false;

  function Robot(rdfUrl) {
    this.rdfUrl = rdfUrl;
    $.getJSON(rdfUrl, rdfLoadingCallback);
  }

  return Robot;

})();

rdfLoadingCallback = function(description) {
  console.log('loading description \"' + description.name + '\"');
  bodyQueue = bodyQueue.concat(description.bodies);
  loader = new THREE.JSONLoader();
  return loadNextBody();
};

loadNextBody = function() {
  var path;
  if (bodyQueue.length > 0) {
    path = baseUrl + bodyQueue[0]['de.fumanoids.message.BodyExternal.path'];
    console.log('adding body #' + bodyQueue[0].id + ' loaded from ' + path);
    return loader.load(path, addBody);
  }
};

addBody = function(geometry) {
  var body, zmesh;
  body = bodyQueue[0];
  bodyQueue.shift();
  zmesh = new THREE.Mesh(geometry, new THREE.MeshFaceMaterial());
  zmesh.position.set(0, 5, 0);
  zmesh.scale.set(5, 5, 5);
  scene.add(zmesh);
  return loadNextBody();
};
