// Generated by CoffeeScript 1.3.3
var matrixFromProto;

matrixFromProto = function(protoMatrix) {
  var matrix;
  return matrix = new THREE.Matrix4(protoMatrix.x11, protoMatrix.x12, protoMatrix.x13, protoMatrix.x14, protoMatrix.x21, protoMatrix.x22, protoMatrix.x23, protoMatrix.x24, protoMatrix.x31, protoMatrix.x32, protoMatrix.x33, protoMatrix.x34, protoMatrix.x41, protoMatrix.x42, protoMatrix.x43, protoMatrix.x44);
};
